### PR TITLE
Handle 'Backspace' block elements removal on Android

### PR DESCRIPTION
**Pull request by f1ames**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Type: Handle `Backspace` block elements removal on Android. Closes ckeditor/ckeditor5/issues/1106. Closes ckeditor/ckeditor5/issues/1130.

---

### Additional information

The main issues with the <kbd>Backsapce</kbd> on Android are described in https://github.com/ckeditor/ckeditor5/issues/614#issuecomment-400333956 and https://github.com/ckeditor/ckeditor5/issues/614#issuecomment-400656927 and they are the main reason why the solution is implemented in a way it is (of course apart from the fact that every key press has `229` key code on Android).

**To sum up how the flow looks like in a general perspective**:

1. Special [`injectAndroidBackspaceMutationsHandling` is initialised inside `Delete` plugin](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/delete.js#L45).
1. It has [`selection` change](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L37) and [`mutations`](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L51) listener:
    * `selection` change listener stores previous and current selection every time it changes, it also stores timestamp of the latest change
    * `mutations` listener checks if given mutations are the _block removal mutations_ and acts accordingly
1. On every _block removal mutation_ selected content is removed. It might be current or previous selected content [depending on selection state](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L100).

There is also one unrelated but similar issue - https://github.com/ckeditor/ckeditor5/issues/1127

### CODE REVIEW

**Comment by f1ames** [comment]
> Does this patch is somehow targeted at Android? Or will it handle mutations on all browsers?

There is no environment/device detection so it will be fired on all devices/browsers. However, it handles very specific cases so it shouldn't interfere with the current flow for other browsers (and if such case will happen it will be handled same as on Android which seems to make sense as it will provide consistent behaviour).

Of course there always may be some strange/edge cases... So if something gets removed unexpectedly (not only on <kbd>Backspace</kbd>, but in general), it means it might be caused by this fix (cc @Mgsy).

**Comment by Mgsy** [comment]
## Android
### Steps to reproduce
1. Open the article sample.
1. Select the word `Paragraph`.
1. Activate `Bold`.
1. Press `Backspace`.

## Current result
The whole block is removed and the selection moves to the previous block.

## Expected result
Only word `Paragraph` is removed.

**Comment by Mgsy** [comment]
### Android
## Steps to reproduce
1. Open the article sample.
1. Put the caret at the beginning of the word `Paragraph`.
1. Activate `Bold`.
1. Press `Backspace`.

## Current result
Nothing happens.

## Expected result
The paragraph is merged to the previous block.

## Notes
It requires 8x backspace to merge the blocks.

**Comment by Reinmar** [comment]
> It requires 8x backspace to merge the blocks.

Ouch... That's the inline filler. Nothing blocking for this PR but we'll need to figure out how to get rid of it.

**Comment by Mgsy** [comment]
### Android
## Steps to reproduce
1. Open the article sample.
2. Make the following selection:
```
Bold Italic Link[
* UL List] item 1
```
3. Press `Backspace`.
_Optional further steps if works as expected_:
4. Undo.
5. Click on the selected part of the `UL List item 1` (selection should become as in step 2).
6. Press `Backspace`.

## Current result
`Link` and part of a `Italic` are deleted.

**Comment by f1ames** [comment]
> It requires 8x backspace to merge the blocks.

It might be related to https://github.com/ckeditor/ckeditor5-typing/issues/160, where reference to inline filler is lost, I will check it.

**Comment by Mgsy** [comment]
I've tested it in all desktop browsers and didn't notice any bugs related to this change. On Android also works good, except cases mentioned above 👌

**Comment by f1ames** [comment]
It looks like Android is a rather tricky environment 😭 I'm able to reproduce all three issues on the current `master` (so without this fix/PR). I decided to describe each issue in a separate comment as it got quite long along the way.

## First issue - https://github.com/ckeditor/ckeditor5-typing/pull/165#issuecomment-402956411:

It happens randomly with and without this PR. There are basically two different flows - one results in correct paragraph removal (so empty paragraph is left) and the other one in entire paragraph removal.

**Correct flow**:
1. [`Keydown handler`](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectunsafekeystrokeshandling.js#L47) is fired and [stopped because selection is collapsed](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectunsafekeystrokeshandling.js#L64).
1. [`Android mutations` handler](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L51) is fired, but not triggered because the only [mutation does not contain container removal](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L52): `[ { type: "children", oldChildren: Array(1), newChildren: Array(1), node: ContainerElement } ]` - `AttributeElement:strong` is replaced with `Element:br` here.
1. [Regular `mutations handler`](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injecttypingmutationshandling.js#L94) is fired processing given mutation which results in [executing `input command`](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injecttypingmutationshandling.js#L177).

**Incorrect flow**:
1. `Keydown handler` is fired. Selection is not collapsed so the [whole selected content gets removed](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectunsafekeystrokeshandling.js#L80) (here the paragraph gets lost).
1. `Android mutations` handler is fired. The mutations show container removal so it is processed and [`delete command` is triggered](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L53). The only effect here is the change of selection position.
1. Because `Android mutations` handler was fired, the regular one is not. However,  even without [stoping `mutations event`](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injectandroidbackspacemutationshandling.js#L56), regular `mutations handler` will not be executed because `mutations` [are not `safe for text mutation`](https://github.com/ckeditor/ckeditor5-typing/blob/d1daaa285b34c820e16cddc70ce8d6ba06619027/src/utils/injecttypingmutationshandling.js#L142) as they contain both `children` and `text` type - `[ { type: "text", oldText: "Heading 1", newText: "H", node: Text }, { type: "children", oldChildren: Array(7), newChildren: Array(6), node: RootEditableElement } ]`

So it seems the problem is related to unstable selection which is different for identical set of operations, this might be the same problem as https://github.com/ckeditor/ckeditor5/issues/1127. The other thing is that maybe adjusting how `keydown` handler removes content may help, but I'm not sure about this

gif-180706_124639

**Comment by f1ames** [comment]
## Second issue - https://github.com/ckeditor/ckeditor5-typing/pull/165#issuecomment-402957454:

This is related to #160 - after last step (pressing <kbd>Backsace</kbd>), the `Uncaught CKEditorError: view-renderer-filler-was-lost: The inline filler node was lost.` error is thrown. The inline filler reference gets lost in the `Renderer` so you have to delete it manually which makes 8th press merging lines (as 7 presses before were deleting 7 `ZWS`'es).

_In this scenario the above fix is not triggered at all because merging lines is handled natively._ 🤔 

gif-180706_125326
_This .gif was recorded on latest `master` without this PR_.

**Comment by f1ames** [comment]
## Third issue - https://github.com/ckeditor/ckeditor5-typing/pull/165#issuecomment-402963704:

This is the same case as https://github.com/ckeditor/ckeditor5/issues/1127. Selection sometimes is collapse, sometimes not which triggers removing selected content by `injectUnsafeKeystrokesHandling`. See https://github.com/ckeditor/ckeditor5/issues/1127 for detailed description.

_The Android mutations handler added in this PR is not triggered in the invalid case (non-collapsed selection) at all._

gif-180706_130121
_This .gif was recorded on latest `master` without this PR_.

**Pull request merged**
